export const QUOTES = [
  { id: "1", text: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
  { id: "2", text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { id: "3", text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { id: "4", text: "Your limitation—it's only your imagination.", author: "Unknown" },
  { id: "5", text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { id: "6", text: "Great things never come from comfort zones.", author: "Unknown" },
  { id: "7", text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { id: "8", text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
  { id: "9", text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { id: "10", text: "Dream bigger. Do bigger.", author: "Unknown" },
  { id: "11", text: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
  { id: "12", text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { id: "13", text: "Do something today that your future self will thank you for.", author: "Unknown" },
  { id: "14", text: "Little things make big days.", author: "Unknown" },
  { id: "15", text: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { id: "16", text: "Don’t wait for opportunity. Create it.", author: "Unknown" },
  { id: "17", text: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { id: "18", text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { id: "19", text: "Dream it. Believe it. Build it.", author: "Unknown" },
  { id: "20", text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { id: "21", text: "A little progress each day adds up to big results.", author: "Unknown" },
  { id: "22", text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { id: "23", text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { id: "24", text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { id: "25", text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { id: "26", text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { id: "27", text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { id: "28", text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { id: "29", text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { id: "30", text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { id: "31", text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { id: "32", text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { id: "33", text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { id: "34", text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { id: "35", text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { id: "36", text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { id: "37", text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { id: "38", text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { id: "39", text: "Stop chasing the money and start chasing the passion.", author: "Tony Hsieh" },
  { id: "40", text: "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable.", author: "John Wooden" },
  { id: "41", text: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
  { id: "42", text: "Success is getting what you want, happiness is wanting what you get.", author: "W.P. Kinsella" },
  { id: "43", text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
  { id: "44", text: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { id: "45", text: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { id: "46", text: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
  { id: "47", text: "Experience is a hard teacher because she gives the test first, the lesson afterwards.", author: "Vernon Sanders Law" },
  { id: "48", text: "To know how much there is to know is the beginning of learning to live.", author: "Dorothy West" },
  { id: "49", text: "Goal setting is the secret to a compelling future.", author: "Tony Robbins" },
  { id: "50", text: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell" },
  { id: "51", text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { id: "52", text: "I’m a greater believer in luck, and I find the harder I work the more I have of it.", author: "Thomas Jefferson" },
  { id: "53", text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
  { id: "54", text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { id: "55", text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { id: "56", text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { id: "57", text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { id: "58", text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { id: "59", text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { id: "60", text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { id: "61", text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { id: "62", text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { id: "63", text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { id: "64", text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { id: "65", text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { id: "66", text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { id: "67", text: "People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily.", author: "Zig Ziglar" },
  { id: "68", text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { id: "69", text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { id: "70", text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { id: "71", text: "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.", author: "Carl Bard" },
  { id: "72", text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { id: "73", text: "The most common way people give up their power is by thinking they don’t have any.", author: "Alice Walker" },
  { id: "74", text: "The mind is everything. What you think you become.", author: "Buddha" },
  { id: "75", text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { id: "76", text: "An unexamined life is not worth living.", author: "Socrates" },
  { id: "77", text: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { id: "78", text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { id: "79", text: "Winning isn’t everything, but wanting to win is.", author: "Vince Lombardi" },
  { id: "80", text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { id: "81", text: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
  { id: "82", text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { id: "83", text: "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { id: "84", text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { id: "85", text: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
  { id: "86", text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { id: "87", text: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { id: "88", text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { id: "89", text: "People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily.", author: "Zig Ziglar" },
  { id: "90", text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { id: "91", text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { id: "92", text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { id: "93", text: "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.", author: "Carl Bard" },
  { id: "94", text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { id: "95", text: "The most common way people give up their power is by thinking they don’t have any.", author: "Alice Walker" },
  { id: "96", text: "The mind is everything. What you think you become.", author: "Buddha" },
  { id: "97", text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { id: "98", text: "An unexamined life is not worth living.", author: "Socrates" },
  { id: "99", text: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { id: "100", text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { id: "101", text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { id: "102", text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { id: "103", text: "Our greatest glory is not in never failing, but in rising up every time we fail.", author: "Ralph Waldo Emerson" },
  { id: "104", text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
  { id: "105", text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { id: "106", text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { id: "107", text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { id: "108", text: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
  { id: "109", text: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.", author: "Arnold Schwarzenegger" },
  { id: "110", text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { id: "111", text: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
  { id: "112", text: "The greater the difficulty, the more glory in surmounting it.", author: "Molière" },
  { id: "113", text: "Life is a mountain. Your goal is to find your path, not to reach the top.", author: "Unknown" },
  { id: "114", text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama" },
  { id: "115", text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso" },
  { id: "116", text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { id: "117", text: "The secret to success is to know something nobody else knows.", author: "Aristotle Onassis" },
  { id: "118", text: "Do not wait to strike till the iron is hot; but make the iron hot by striking.", author: "William Butler Yeats" },
  { id: "119", text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { id: "120", text: "The more difficult the victory, the greater the happiness in winning.", author: "Pelé" },
  { id: "121", text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { id: "122", text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to just try one more time.", author: "Thomas Edison" },
  { id: "123", text: "Infuse your life with action. Don't wait for it to happen. Make it happen.", author: "Bradley Whitford" },
  { id: "124", text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { id: "125", text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { id: "126", text: "Today's actions are tomorrow's results.", author: "Unknown" },
  { id: "127", text: "The greatest measure of a man is what he does when he has nothing to lose.", author: "Unknown" },
  { id: "128", text: "Courage is resistance to fear, mastery of fear—not absence of fear.", author: "Mark Twain" },
  { id: "129", text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie" },
  { id: "130", text: "If you genuinely want something, don’t wait for it—teach yourself to be impatient.", author: "Gurbaksh Chahal" },
  { id: "131", text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { id: "132", text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
  { id: "133", text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { id: "134", text: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier" },
  { id: "135", text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { id: "136", text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", author: "Vince Lombardi" },
  { id: "137", text: "Excellence is not a skill. It is an attitude.", author: "Ralph Marston" },
  { id: "138", text: "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.", author: "Vince Lombardi" },
  { id: "139", text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { id: "140", text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { id: "141", text: "Do not wait for the perfect time and place to enter, for you are already onstage.", author: "Unknown" },
  { id: "142", text: "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.", author: "Confucius" },
  { id: "143", text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
  { id: "144", text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { id: "145", text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
  { id: "146", text: "Worry about being effective, not busy.", author: "Tim Ferriss" },
  { id: "147", text: "You can't have a better tomorrow if you are thinking about yesterday all the time.", author: "Charles Kettering" },
  { id: "148", text: "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this that in all things distinguishes the strong soul from the weak.", author: "Thomas Carlyle" },
  { id: "149", text: "The starting point of all achievement is desire.", author: "Napoleon Hill" },
  { id: "150", text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
  { id: "151", text: "We become what we think about.", author: "Earl Nightingale" },
  { id: "152", text: "The mind, once stretched by a new idea, never returns to its original dimensions.", author: "Oliver Wendell Holmes Sr." },
  { id: "153", text: "If you are not moving forward, you are moving backward.", author: "Unknown" },
  { id: "154", text: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa" },
  { id: "155", text: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
  { id: "156", text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
  { id: "157", text: "Take the risk or lose the chance.", author: "Unknown" },
  { id: "158", text: "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible, inevitable battles—that's where it's all at.", author: "Jesse Owens" },
  { id: "159", text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley" },
  { id: "160", text: "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!", author: "T. Harv Eker" },
  { id: "161", text: "Put your heart, mind, and soul into even your smallest acts. This is the secret of success.", author: "Swami Sivananda" },
  { id: "162", text: "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.", author: "Mark Twain" },
  { id: "163", text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { id: "164", text: "The key to success is to start before you are ready.", author: "Marie Forleo" },
  { id: "165", text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { id: "166", text: "The future starts today, not tomorrow.", author: "Pope John Paul II" },
  { id: "167", text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { id: "168", text: "The power of imagination makes us infinite.", author: "John Muir" },
  { id: "169", text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso" },
  { id: "170", text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
  { id: "171", text: "We aim above the mark to hit the mark.", author: "Ralph Waldo Emerson" },
  { id: "172", text: "Always do your best. What you plant now, you will harvest later.", author: "Og Mandino" },
  { id: "173", text: "Try to be a rainbow in someone’s cloud.", author: "Maya Angelou" },
  { id: "174", text: "The way to gain a good reputation is to endeavor to be what you desire to appear.", author: "Socrates" },
  { id: "175", text: "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", author: "Oprah Winfrey" },
  { id: "176", text: "We can't help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { id: "177", text: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby" },
  { id: "178", text: "It’s not what you look at that matters, it’s what you see.", author: "Henry David Thoreau" },
  { id: "179", text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { id: "180", text: "To be the best, you must be able to handle the worst.", author: "Wilson Kanadi" },
  { id: "181", text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { id: "182", text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
  { id: "183", text: "A ship in the harbor is safe, but that is not what a ship is built for.", author: "John A. Shedd" },
  { id: "184", text: "The best way out is always through.", author: "Robert Frost" },
  { id: "185", text: "Setting goals for yourself is the most important thing you can do to improve your life.", author: "Unknown" },
  { id: "186", text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { id: "187", text: "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author: "George Bernard Shaw" },
  { id: "188", text: "If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
  { id: "189", text: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau" },
  { id: "190", text: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
  { id: "191", text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { id: "192", text: "The journey is the reward.", author: "Chinese Proverb" },
  { id: "193", text: "Don't be afraid to fail. Be afraid not to try.", author: "Unknown" },
  { id: "194", text: "I choose to make the rest of my life the best of my life.", author: "Unknown" },
  { id: "195", text: "It's hard to beat a person who never gives up.", author: "Babe Ruth" },
  { id: "196", text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
  { id: "197", text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { id: "198", text: "The best way to appreciate your job is to imagine yourself without one.", author: "Oscar Wilde" },
  { id: "199", text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
  { id: "200", text: "The only source of knowledge is experience.", author: "Albert Einstein" },
];